-- Littering, B41 Continued
-- (41.68)(07may22)


-- debug
--TweakItem("Base.Needle","Icon", "Base.Worm");
--Adjust("Base.Needle","Icon", "Base.Worm");


-- replace on use
TweakItem("Base.Apple","ReplaceOnUse", "LitteringB41.AppleCore");
TweakItem("Base.BakingSoda","ReplaceOnUse", "LitteringB41.BakingSodaEmpty");
TweakItem("Base.Banana","ReplaceOnUse", "LitteringB41.BananaPeel");
TweakItem("Base.Bass","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.BaitFish","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Catfish","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Chicken","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.ChickenFried","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.DeadBird","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.DeadMouse","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.DeadRabbit","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.DeadRat","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.DeadSquirrel","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.FishFillet","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.FrogMeat","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Ham","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.MuttonChop","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Panfish","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Perch","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Pike","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.PorkChop","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Rabbitmeat","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Salmon","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Smallanimalmeat","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Smallbirdmeat","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Steak","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Sunfish","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Trout","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.Corndog","ReplaceOnUse", "LitteringB41.CorndogStick");
TweakItem("Base.Lemon","ReplaceOnUse", "LitteringB41.FruitRindLemon");
TweakItem("Base.Lime","ReplaceOnUse", "LitteringB41.FruitRindLime");
TweakItem("Base.Orange","ReplaceOnUse", "LitteringB41.FruitRindOrange");
TweakItem("Base.Pineapple","ReplaceOnUse", "LitteringB41.FruitRindPineapple");
TweakItem("Base.Watermelon","ReplaceOnUse", "LitteringB41.FruitRindMelon");
TweakItem("Base.Milk","ReplaceOnUse", "LitteringB41.MilkEmpty");
TweakItem("Base.JuiceBox","ReplaceOnUse", "LitteringB41.JuiceBoxEmpty");
TweakItem("Base.Icecream","ReplaceOnUse", "LitteringB41.TubIcecreamEmpty");
TweakItem("Base.IcecreamMelted","ReplaceOnUse", "LitteringB41.TubIcecreamEmpty");
TweakItem("Base.Candycane","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.MintCandy","ReplaceOnUse", "LitteringB41.MintCandyWrapper");
TweakItem("Base.Cereal","ReplaceOnUse", "LitteringB41.CerealEmpty");
TweakItem("Base.CookieChocolateChip","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.CookieJelly","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.SunflowerSeeds","ReplaceOnUse", "LitteringB41.SunflowerShells");
TweakItem("Base.Lollipop","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.CandyPackage","ReplaceOnUse", "LitteringB41.CandyPackageEmpty");
TweakItem("Base.Popcorn","ReplaceOnUse", "LitteringB41.PopcornBagEmpty");
TweakItem("Base.Cupcake","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Chocolate","ReplaceOnUse", "LitteringB41.ChocolateWrapper");
TweakItem("Base.WildEggs","ReplaceOnUse", "LitteringB41.Eggshells");
TweakItem("Base.WildEggs","ReplaceOnUse", "LitteringB41.Eggshells");
TweakItem("Base.WildEggs","ReplaceOnUse", "LitteringB41.Eggshells");
TweakItem("Base.WildEggs","ReplaceOnUse", "LitteringB41.Eggshells");
TweakItem("Base.Crisps","ReplaceOnUse", "LitteringB41.CrispsEmpty");
TweakItem("Base.Crisps2","ReplaceOnUse", "LitteringB41.Crisps2Empty");
TweakItem("Base.Crisps3","ReplaceOnUse", "LitteringB41.Crisps3Empty");
TweakItem("Base.Crisps4","ReplaceOnUse", "LitteringB41.Crisps4Empty");
TweakItem("Base.PeanutButter","ReplaceOnUse", "LitteringB41.PeanutButterEmpty");
TweakItem("Base.PiePumpkin","ReplaceOnUse", "LitteringB41.PieCartonEmpty");
TweakItem("Base.Peanuts","ReplaceOnUse", "LitteringB41.PeanutShells");
TweakItem("Base.TVDinner","ReplaceOnUse", "LitteringB41.TVDinnerPackage");
TweakItem("Base.EggCarton","ReplaceOnUse", "LitteringB41.EggCartonEmpty");
TweakItem("Base.Coffee2","ReplaceOnUse", "LitteringB41.CoffeeEmpty");
TweakItem("Base.Teabag2","ReplaceOnUse", "LitteringB41.UsedTeabag");
TweakItem("Base.Macandcheese","ReplaceOnUse", "LitteringB41.MacBoxEmpty");
TweakItem("Base.Honey","ReplaceOnUse", "LitteringB41.HoneyBottleEmpty");
TweakItem("Base.Sugar","ReplaceOnUse", "LitteringB41.SugarEmpty");
TweakItem("Base.BrownSugar","ReplaceOnUse", "LitteringB41.BrownSugarEmpty");
TweakItem("Base.Yoghurt","ReplaceOnUse", "LitteringB41.YogurtEmpty");
TweakItem("Base.Mustard","ReplaceOnUse", "LitteringB41.MustardEmpty");
TweakItem("Base.Ketchup","ReplaceOnUse", "LitteringB41.KetchupEmpty");
TweakItem("Base.Marinara","ReplaceOnUse", "LitteringB41.MarinaraEmpty");
TweakItem("Base.Processedcheese","ReplaceOnUse", "LitteringB41.CheeseWrapper");
TweakItem("Base.Modjeska","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Fries","ReplaceOnUse", "LitteringB41.FriesCartonEmpty");
TweakItem("Base.BagelPlain","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.BagelPoppy","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.BagelSesame","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Bread","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Baguette","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Burrito","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.CakeBlackForest","ReplaceOnUse", "LitteringB41.CakeCartonEmpty");
TweakItem("Base.CakeCarrot","ReplaceOnUse", "LitteringB41.CakeCartonEmpty");
TweakItem("Base.CakeCheeseCake","ReplaceOnUse", "LitteringB41.CakeCartonEmpty");
TweakItem("Base.CakeChocolate","ReplaceOnUse", "LitteringB41.CakeCartonEmpty");
TweakItem("Base.CakeRedVelvet","ReplaceOnUse", "LitteringB41.CakeCartonEmpty");
TweakItem("Base.CakeStrawberryShortcake","ReplaceOnUse", "LitteringB41.CakeCartonEmpty");
TweakItem("Base.ChickenFoot","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.ChocolateChips","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.CocoaPowder","ReplaceOnUse", "LitteringB41.CocoaPowderEmpty");
TweakItem("Base.CookiesChocolate","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.CookiesOatmeal","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.CookiesShortbread","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Croissant","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.DoughnutChocolate","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.DoughnutFrosted","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.DoughnutJelly","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.DoughnutPlain","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Grapefruit","ReplaceOnUse", "LitteringB41.FruitRindOrange");
TweakItem("Base.Hotsauce","ReplaceOnUse", "LitteringB41.HotsauceBottleEmpty");
TweakItem("Base.Icing","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Lobster","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.MapleSyrup","ReplaceOnUse", "LitteringB41.MapleSyrupEmpty");
TweakItem("Base.MuffinFruit","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.OilVegetableEmpty","ReplaceOnUse", "LitteringB41.OilVegetableEmpty");
TweakItem("Base.Oysters","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.RiceVinegar","ReplaceOnUse", "LitteringB41.RiceVinegarEmpty");
TweakItem("Base.Soysauce","ReplaceOnUse", "LitteringB41.SoysauceEmpty");
TweakItem("Base.Crackers","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.GrahamCrackers","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Gravy","ReplaceOnUse", "LitteringB41.GravyBoat");
TweakItem("Base.Gum","ReplaceOnUse", "LitteringB41.GumWrapper");
TweakItem("Base.JamFruit","ReplaceOnUse", "LitteringB41.JamFruitEmpty");
TweakItem("Base.JamMarmalade","ReplaceOnUse", "LitteringB41.JamMarmaladeEmpty");
TweakItem("Base.Marshmallows","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.OystersFried","ReplaceOnUse", "LitteringB41.BoneScraps");
TweakItem("Base.GranolaBar","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Pumpkin","ReplaceOnUse", "LitteringB41.FruitRindOrange");
TweakItem("Base.HalloweenPumpkin","ReplaceOnUse", "LitteringB41.FruitRindOrange");
TweakItem("Base.CinnamonRoll","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.LicoriceBlack","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.LicoriceRed","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Painauchocolat","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.Perogies","ReplaceOnUse", "LitteringB41.PlasticWrapperGeneric");
TweakItem("Base.DriedBlackBeans","ReplaceOnUse", "LitteringB41.DriedBlackBeansEmpty");
TweakItem("Base.DriedChickpeas","ReplaceOnUse", "LitteringB41.DriedChickpeasEmpty");
TweakItem("Base.DriedKidneyBeans","ReplaceOnUse", "LitteringB41.DriedKidneyBeansEmpty");
TweakItem("Base.DriedLentils","ReplaceOnUse", "LitteringB41.DriedLentilsEmpty");
TweakItem("Base.DriedSplitPeas","ReplaceOnUse", "LitteringB41.DriedSplitPeasEmpty");
TweakItem("Base.DriedWhiteBeans","ReplaceOnUse", "LitteringB41.DriedWhiteBeansEmpty");
TweakItem("Base.ConcretePowder","ReplaceOnUse", "LitteringB41.ConcretePowderEmpty");
TweakItem("Base.PlasterPowder","ReplaceOnUse", "LitteringB41.PlasterPowderEmpty");
TweakItem("Base.GunPowder","ReplaceOnUse", "LitteringB41.GunpowderJarEmpty");
TweakItem("Base.Sparklers","ReplaceOnUse", "LitteringB41.SparklerBoxEmpty");
TweakItem("Base.Scotchtape","ReplaceOnUse", "LitteringB41.ScotchtapeEmpty");
TweakItem("Base.Corn","ReplaceOnUse", "LitteringB41.CornCob");
TweakItem("Base.Peach","ReplaceOnUse", "LitteringB41.FruitPits");
TweakItem("Base.Pear","ReplaceOnUse", "LitteringB41.FruitPits");
TweakItem("Base.Cherry","ReplaceOnUse", "LitteringB41.FruitPits");
TweakItem("Base.Avocado","ReplaceOnUse", "LitteringB41.FruitPits");
TweakItem("Base.Salt","ReplaceOnUse", "LitteringB41.SaltShakerEmpty");
TweakItem("Base.Pepper","ReplaceOnUse", "LitteringB41.PepperShakerEmpty");
TweakItem("Base.Rice","ReplaceOnUse", "LitteringB41.RiceBagEmpty");
TweakItem("Base.Pasta","ReplaceOnUse", "LitteringB41.SpaghetBoxEmpty");
TweakItem("Base.OatsRaw","ReplaceOnUse", "LitteringB41.CanOfOatsEmpty");
TweakItem("Base.Tissue","ReplaceOnUse", "LitteringB41.TissueUsed");
TweakItem("Base.Cigarettes","ReplaceOnUse", "LitteringB41.CigaretteButt");

-- replace on deplete
TweakItem("Base.AlcoholWipes","ReplaceOnDeplete", "LitteringB41.AlcoholWipesEmpty");
TweakItem("Base.Thread","ReplaceOnDeplete", "LitteringB41.ThreadSpool");
TweakItem("Base.Matches","ReplaceOnDeplete", "LitteringB41.MatchesEmpty");
TweakItem("Base.Lighter","ReplaceOnDeplete", "LitteringB41.LighterEmpty");
TweakItem("Base.Charcoal","ReplaceOnDeplete", "LitteringB41.BagOfCharcoalEmpty");
TweakItem("Base.Pills","ReplaceOnDeplete", "LitteringB41.PainkillersEmpty");
TweakItem("Base.PillsAntiDep","ReplaceOnDeplete", "LitteringB41.AntidepressantsEmpty");
TweakItem("Base.PillsBeta","ReplaceOnDeplete", "LitteringB41.BetaBlockersEmpty");
TweakItem("Base.PillsSleepingTablets","ReplaceOnDeplete", "LitteringB41.SleepingPillsEmpty");
TweakItem("Base.Thread","ReplaceOnDeplete", "LitteringB41.ThreadSpool");
TweakItem("Base.CleaningLiquid2","ReplaceOnDeplete", "LitteringB41.CleaningLiquidEmpty");
-- TweakItem("Base.Cologne","ReplaceOnDeplete", "LitteringB41.CologneEmpty");
-- TweakItem("Base.Perfume","ReplaceOnDeplete", "LitteringB41.PerfumeEmpty");
-- TweakItem("Base.Lipstick","ReplaceOnDeplete", "LitteringB41.LipstickTubeEmpty");
-- TweakItem("Base.MakeupEyeshadow","ReplaceOnDeplete", "LitteringB41.MakeupEyeshadowEmpty");
-- TweakItem("Base.MakeupFoundation","ReplaceOnDeplete", "LitteringB41.MakeupFoundationEmpty");
TweakItem("Base.ToiletPaper","ReplaceOnDeplete", "LitteringB41.ToiletPaperEmpty");
TweakItem("Base.BakingSoda","ReplaceOnDeplete", "LitteringB41.BakingSodaEmpty");
TweakItem("Base.Twine","ReplaceOnDeplete", "LitteringB41.TwineSpool");
TweakItem("Base.Woodglue","ReplaceOnDeplete", "LitteringB41.WoodGlueEmpty");
TweakItem("Base.Glue","ReplaceOnDeplete", "LitteringB41.GlueEmpty");
TweakItem("Base.DuctTape","ReplaceOnDeplete", "LitteringB41.DuctTapeEmpty");
TweakItem("Base.Disinfectant","ReplaceOnDeplete", "LitteringB41.DisinfectantEmpty");
TweakItem("Base.AlcoholWipes","ReplaceOnDeplete", "LitteringB41.AlcoholWipesEmpty");
TweakItem("Base.PillsVitamins","ReplaceOnDeplete", "LitteringB41.VitaminsEmpty");
TweakItem("Base.Antibiotics","ReplaceOnDeplete", "LitteringB41.AntibioticsBlisterEmpty");
TweakItem("Base.FishingLine","ReplaceOnDeplete", "LitteringB41.FishingLineEmpty");
TweakItem("Base.Vinegar","ReplaceOnDeplete", "LitteringB41.VinegarEmpty");
TweakItem("Base.WeldingRods","ReplaceOnDeplete", "LitteringB41.WeldingRodsEmpty");
TweakItem("Base.HairDyeBlack","ReplaceOnDeplete", "LitteringB41.HairDyeBlackEmpty");
TweakItem("Base.HairDyeBlonde","ReplaceOnDeplete", "LitteringB41.HairDyeBlondeEmpty");
TweakItem("Base.HairDyeBlue","ReplaceOnDeplete", "LitteringB41.HairDyeBlueEmpty");
TweakItem("Base.HairDyeLightBrown","ReplaceOnDeplete", "LitteringB41.HairDyeBrownEmpty");
TweakItem("Base.HairDyeGinger","ReplaceOnDeplete", "LitteringB41.HairDyeGingerEmpty");
TweakItem("Base.HairDyeGreen","ReplaceOnDeplete", "LitteringB41.HairDyeGreenEmpty");
TweakItem("Base.HairDyePink","ReplaceOnDeplete", "LitteringB41.HairDyePinkEmpty");
TweakItem("Base.HairDyeRed","ReplaceOnDeplete", "LitteringB41.HairDyeRedEmpty");
TweakItem("Base.HairDyeWhite","ReplaceOnDeplete", "LitteringB41.HairDyeWhiteEmpty");
TweakItem("Base.HairDyeYellow","ReplaceOnDeplete", "LitteringB41.HairDyeYellowEmpty");
TweakItem("Base.Extinguisher","ReplaceOnDeplete", "LitteringB41.ExtinguisherEmpty");

-- Other tweaks
TweakItem("Base.Charcoal","Icon", "BagOfCharcoal");
TweakItem("Base.Antibiotics","Icon", "AntibioticsBlisterV2");
TweakItem("Base.Antibiotics","WorldStaticModel", "AntibioticsBlister");
TweakItem("Base.PillsAntiDep","WorldStaticModel", "AntidepressantsV2");
-- TweakItem("Base.Antibiotics","Type", "Drainable");
-- TweakItem("Base.Antibiotics","UseDelta", "0.25");
-- TweakItem("Base.PillsVitamins","UseDelta", "0.25");
-- TweakItem("Base.PillsVitamins","FatigueChange", "-25");
TweakItem("Base.Yeast","Icon", "YeastPacket");
TweakItem("Base.AlcoholWipes","Icon", "WipesV2");
TweakItem("Base.PiePumpkin","Icon", "PieCartonPumpkin");
TweakItem("Base.PiePumpkin","WorldStaticModel", "PieCartonPumpkin");
TweakItem("Base.CakeBlackForest","Icon", "CakeCartonBlackForest");
TweakItem("Base.CakeCheeseCake","Icon", "CakeCartonWhiteFrosting");
TweakItem("Base.CakeChocolate","Icon", "CakeCartonChocolate");
TweakItem("Base.CakeRedVelvet","Icon", "CakeCartonWhiteFrosting");
TweakItem("Base.CakeStrawberryShortcake","Icon", "CakeCartonWhiteFrosting");
TweakItem("Base.CakeCarrot","Icon", "CakeCartonGeneric");
TweakItem("Base.CakeBlackForest","WorldStaticModel", "CakeCartonBlackForest");
TweakItem("Base.CakeCheeseCake","WorldStaticModel", "CakeCartonCheesecake");
TweakItem("Base.CakeChocolate","WorldStaticModel", "CakeCartonChocolate");
TweakItem("Base.CakeRedVelvet","WorldStaticModel", "CakeCartonRedVelvet");
TweakItem("Base.CakeStrawberryShortcake","WorldStaticModel", "CakeCartonCheesecake");
TweakItem("Base.CakeCarrot","WorldStaticModel", "CakeCartonCarrot");
TweakItem("Base.Hotsauce","Icon", "HotsauceV2");
TweakItem("Base.Book", "ReplaceOnUse", "LitteringB41.BookTorn");
TweakItem("Base.ComicBook", "ReplaceOnUse", "LitteringB41.ComicBookTorn");
TweakItem("Base.HottieZ", "ReplaceOnUse", "LitteringB41.MagazineNudie1Gross");
TweakItem("Base.Magazine", "ReplaceOnUse", "LitteringB41.MagazineTorn");
TweakItem("Base.MagazineCrossword1", "ReplaceOnUse", "LitteringB41.Crossword1Used");
TweakItem("Base.MagazineCrossword2", "ReplaceOnUse", "LitteringB41.Crossword2Used");
TweakItem("Base.MagazineCrossword3", "ReplaceOnUse", "LitteringB41.Crossword3Used");
TweakItem("Base.MagazineWordSearch1", "ReplaceOnUse", "LitteringB41.WordSearch1Used");
TweakItem("Base.MagazineWordSearch2", "ReplaceOnUse", "LitteringB41.WordSearch2Used");
TweakItem("Base.MagazineWordSearch3", "ReplaceOnUse", "LitteringB41.WordSearch3Used");
TweakItem("Base.Newspaper", "ReplaceOnUse", "LitteringB41.NewspaperTorn");
TweakItem("Base.TVMagazine", "ReplaceOnUse", "LitteringB41.MagazineTorn");
TweakItem("Base.BakingSoda","Icon", "BakingSodaFull");
TweakItem("Base.DriedBlackBeans","WorldStaticModel", "DriedBlackBeans_Ground");
TweakItem("Base.Gravy","WorldStaticModel", "Gravy");
TweakItem("Base.GravyMix","WorldStaticModel", "GravyMix");
TweakItem("Base.Hotsauce","WorldStaticModel", "Hotsauce");
TweakItem("Base.PillsBeta","WorldStaticModel", "BetaBlockersV2");
TweakItem("Base.Charcoal","WorldStaticModel", "BagOfCharcoal");
TweakItem("Base.Magazine","WorldStaticModel", "Magazine2");
TweakItem("Base.ComicBook","WorldStaticModel", "Magazine2");
TweakItem("Base.Bullets38Box","Icon", "38AmmoBoxV2");
TweakItem("Base.Bullets44Box","Icon", "44AmmoBoxV2");
TweakItem("Base.Bullets45Box","Icon", "45AmmoBoxV2");
TweakItem("Base.Bullets44Box","Icon", "44AmmoBoxV2");
TweakItem("Base.223Box","Icon", "223AmmoBoxV2");
TweakItem("Base.308Box","Icon", "308AmmoBoxV2");
TweakItem("Base.556Box","Icon", "556AmmoBoxV2");
TweakItem("Base.223Box","WorldStaticModel", "RifleAmmo223");
TweakItem("Base.308Box","WorldStaticModel", "RifleAmmo308");
TweakItem("Base.556Box","WorldStaticModel", "RifleAmmo556");
TweakItem("Base.Pasta","Icon", "SpaghetBox");
TweakItem("Base.Pasta","WorldStaticModel", "SpaghetBox");
TweakItem("Base.OilOlive","WorldStaticModel", "OliveOilEmpty");
TweakItem("Base.Yeast","WorldStaticModel", "YeastPacket");


-- PATCH WORK:
--Def's LTS:

function Adjust(Name, Property, Value)
  Item = ScriptManager.instance:getItem(Name)
  Item:DoParam(Property.." = "..Value)
end

if getActivatedMods():contains("DLTS") then
	Adjust("Base.Lighter", "ReplaceOnDeplete", "DLTS.LTSLighterEmpty");
	Adjust("Base.PropaneTank", "ReplaceOnDeplete", "DLTS.LTSPropaneTankEmpty");
	Adjust("Base.Glue", "ReplaceOnDeplete", "DLTS.LTSChemEmpty");
	Adjust("Base.Woodglue", "ReplaceOnDeplete", "DLTS.LTSChemEmpty");
	Adjust("Base.Disinfectant", "ReplaceOnDeplete", "DLTS.LTSChemEmpty");
	Adjust("Base.CleaningLiquid2", "ReplaceOnDeplete", "DLTS.LTSChemEmpty");
	Adjust("Base.Ketchup", "ReplaceOnUse", "DLTS.LTSChemEmpty");
	Adjust("Base.Mustard", "ReplaceOnUse", "DLTS.LTSChemEmpty");
	Adjust("Base.Vinegar", "ReplaceOnDeplete", "Base.EmptyJar");
	Adjust("Base.Coffee2", "ReplaceOnUse", "Base.EmptyJar");
	Adjust("Base.PeanutButter", "ReplaceOnUse", "Base.EmptyJar");
	Adjust("Base.Honey", "ReplaceOnUse", "Base.EmptyJar");
	Adjust("Base.Marinara", "ReplaceOnUse", "Base.EmptyJar");
end